apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nignx
  name: nignx
  namespace: ckad
spec:
  containers:
  - image: nginx
    name: nignx
    ports:
    - containerPort: 80
      protocol: TCP 
    readinessProbe:
      failureThreshold: 5
      httpGet:
        path: /
        port: 80
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 3
      timeoutSeconds: 5
    livenessProbe:
      exec:
        command:
        - ls
        - /var/www/nginx
      initialDelaySeconds: 10
      periodSeconds: 5
    resources: {}
