apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: trd-nginx
  name: trd-nginx
spec:
  securityContext:
    runAsUser: 101
  containers:
  - image: nginx
    name: trd-nginx

