apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: fr-nginx
  name: fr-nginx
spec:
  containers:
  - image: nginx
    name: fr-nginx
    securityContext:
      capabilities:
        add: ["NET_ADMIN", "SYS_TIME"]
