apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nignx
  name: nignx
spec:
  containers:
  - image: nginx
    name: nignx
    livenessProbe:
      exec:
        command:
        - ls
      initialDelaySeconds: 5
      periodSeconds: 5
