apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
  namespace: ckad
spec:
  volumes:
  - name: my-vol
    persistentVolumeClaim: 
      claimName: mypvc
  containers:
  - args:
    - /bin/sh
    - -c
    - sleep 3600
    image: busybox
    name: busybox
    volumeMounts:
    - name: my-vol
      mountPath: /etc/foo

