apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: newnginx
  name: newnginx
spec:
  containers:
  - image: nginx
    name: newnginx
    envFrom:
      - configMapRef:
          name: anotherone
