apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: six-nginx
  name: six-nginx
spec:
  volumes:
  - name: foo
    secret:
      secretName: my-sec
  containers:
  - image: nginx
    name: six-nginx

