apiVersion: v1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
items:
- apiVersion: v1
  kind: ConfigMap
  data:
    app.name: auth-service
    aws.credentials: '"doubledigit"'
    aws.profile: admin
